### ISSUE TITLE
Invitation system for employees

### ISSUE THREAD

**Issue by m-pereira** [comarev/comarev#104]
References: https://github.com/comarev/comarev-dashboard/issues/88

Currently, managers can't add employees to their companies. Let's add an endpoint where a manager can enter a non-registered email. This endpoint might send a nice invitation to this email, returning a 200 status code.
If the email is already registered, the endpoint must return 422, with a message like: `this email: "some@email.com" has already been taken`.

We also need to store the invitations, and for that we can create a new table named `manager_invitations` for example, with the columns: 
- `inviter` (manager's id)
- email
- accepted (boolean)
- refused_at (datetime)

**Comment by aq-simei** [comment]
This issue still available? I would like to try solving it

**Comment by m-pereira** [comment]
Go for it man 🚀

**Comment by m-pereira** [comment]
I was talking to @aq-simei earlier, and we thought this request must do the following:

Check if the user is already registered. If yes, check if this user is already an employee of the company

```
1- Does the user exist?
yes:
  2- check if the user is already an employee of the company
  yes: it returns a 422 error with the message.
  no: create the relationship between the user and the company as `:regular`, and return 200 
no: send an email invitation and return 200
```

@belgamo WDYT?

**Comment by belgamo** [comment]
> I was talking to @aq-simei earlier, and we thought this request must do the following:
> 
> ```
> 1- Does the user exist? ->
> yes:
>   2- check if the user is already an employee of the company ->
>   yes: it returns a 422 error with the message.
>   no: create the relationship between the user and the company as `:regular`, and return 200 
> no: send an email invitation and return 200
> ```
> 
> @belgamo WDYT?

What happens if the user belonged to some other company and left this company? We should consider this case, cause this employee user would be "free" in the system waiting being hired for other companies. So my suggestion is:

```
- Does the user exist? ->
yes:
  - check if the user is already an employee of the company *or another company* ->
    yes: it returns a 422 error with the message.
    no: send an email invitation and return 200 
            - has the user accepted the invitation?
              yes: create the relationship between the user and the company as `:regular`, and return 200 
              no: send an email to the manager informing that the invitation was declined.
no: send an email invitation and return 200
  - has the user accepted the invitation?
    yes: create the relationship between the user and the company as `:regular`, and return 200 
    no: send an email to the manager informing that the invitation was declined.
```
